### ISSUE TITLE
R package installation failed

### ISSUE THREAD

**Issue by zswgzx** [spisakt/pTFCE_spm#2]
Trying to install the pTFCE R package from github, but failed with the following messages:

─  preparing ‘pTFCE’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘pTFCE_0.2.0.0.tar.gz’
   
Installing package into ‘/home/shengwei/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘pTFCE’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error : 'use_package' is not an exported object from 'namespace:devtools'
Error: unable to load R code in package ‘pTFCE’
Execution halted

Already did library(devtools) before this. Any help appreciated.

**Comment by spisakt** [comment]
Solved with v2.01:
https://github.com/spisakt/pTFCE/issues/5#issuecomment-561535729
